### ISSUE TITLE
Drafts are Failing

### ISSUE THREAD

**Issue by triethyl** [South-Paw/action-netlify-deploy#10]
I'm using [this script](https://github.com/South-Paw/action-netlify-deploy#deploying-drafts-of-pull-requests-and-publishing-on-push-to-master) given in the Readme. My production build works fine but the draft releases don't seem to work. It fails on the deployment step.

![image](https://user-images.githubusercontent.com/40622610/79680319-158dae00-822c-11ea-935d-950e33ade475.png)

[Here](https://github.com/QuinchSystems/durbin-client/blob/master/.github/workflows/main.yml) is my workflow script if you need to glance over. 

On pull requests, the Deploy draft to Netlify step is failing. After I merge those failed PRs (forcefully), it works on production. The secrets `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` are already present, because of which the production build isn't failing. But what's going on with the draft releases? It says it can't find the auth token. It would be awesome if you could help me out here.

**Comment by South-Paw** [comment]
Hi,

It looks like it might be because you're merging from a fork into your main repo's `master` branch and hence the action is actually triggered by the fork, not the main repo's `master` branch.

If an action is indeed being triggered by the fork, [then it will not have access to the main repositories secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow).

> With the exception of `GITHUB_TOKEN`, secrets are not passed to the runner when a workflow is triggered from a forked repository.

This is about the only explanation I can think of, as I also have this action running in multiple repo's and drafts deployments are working fine in all of them.

**Comment by triethyl** [comment]
Okay I see this is the issue. But I have definitely seen repositories in which whenever there is a Pull Request from even a forked repository, it automatically generates a draft view of the website over at Netlify. Any idea as to how is that done?

**Comment by South-Paw** [comment]
If the repo is connected directly to Netlify (and you use their build minutes instead of Github's actions) it will probably work as you want it to.

Since this is not an issue with the action and configuring your workflow is out of the scope of this action so I'm going to close the issue.
